/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;

/**
 *
 * @author Realfi
 */
public class jadwal extends javax.swing.JFrame {

    /**
     * Creates new form jadwal
     */
    public jadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        Step1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Step2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Step3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Step4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MilihEdit = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Hapus = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        menutama = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setBackground(new java.awt.Color(172, 226, 219));
        root.setLayout(new java.awt.CardLayout());

        Step1.setBackground(new java.awt.Color(172, 226, 219));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel2.setText("- Step 1 of 4");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel3.setText("Input Data ");

        javax.swing.GroupLayout Step1Layout = new javax.swing.GroupLayout(Step1);
        Step1.setLayout(Step1Layout);
        Step1Layout.setHorizontalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        Step1Layout.setVerticalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(434, Short.MAX_VALUE))
        );

        root.add(Step1, "step1");

        Step2.setBackground(new java.awt.Color(172, 226, 219));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel9.setText("Input Data ");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel10.setText("- Step 2 of 4");

        javax.swing.GroupLayout Step2Layout = new javax.swing.GroupLayout(Step2);
        Step2.setLayout(Step2Layout);
        Step2Layout.setHorizontalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        Step2Layout.setVerticalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(432, Short.MAX_VALUE))
        );

        root.add(Step2, "step2");

        Step3.setBackground(new java.awt.Color(172, 226, 219));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel14.setText("Input Data ");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel15.setText("- Step 3 of 4");

        javax.swing.GroupLayout Step3Layout = new javax.swing.GroupLayout(Step3);
        Step3.setLayout(Step3Layout);
        Step3Layout.setHorizontalGroup(
            Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        Step3Layout.setVerticalGroup(
            Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addContainerGap(434, Short.MAX_VALUE))
        );

        root.add(Step3, "step3");

        Step4.setBackground(new java.awt.Color(172, 226, 219));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel21.setText("Input Data ");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel22.setText("- Step 4 of 4");

        javax.swing.GroupLayout Step4Layout = new javax.swing.GroupLayout(Step4);
        Step4.setLayout(Step4Layout);
        Step4Layout.setHorizontalGroup(
            Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        Step4Layout.setVerticalGroup(
            Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(433, 433, 433))
        );

        root.add(Step4, "step4");

        MilihEdit.setBackground(new java.awt.Color(172, 226, 219));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel26.setText("Edit Entry Data");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Pilih Data");

        javax.swing.GroupLayout MilihEditLayout = new javax.swing.GroupLayout(MilihEdit);
        MilihEdit.setLayout(MilihEditLayout);
        MilihEditLayout.setHorizontalGroup(
            MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilihEditLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MilihEditLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel27))
                    .addComponent(jLabel26))
                .addGap(712, 712, 712))
        );
        MilihEditLayout.setVerticalGroup(
            MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilihEditLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        root.add(MilihEdit, "milihEdit");

        Hapus.setBackground(new java.awt.Color(172, 226, 219));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel28.setText("Hapus Data");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Pilih Data");

        javax.swing.GroupLayout HapusLayout = new javax.swing.GroupLayout(Hapus);
        Hapus.setLayout(HapusLayout);
        HapusLayout.setHorizontalGroup(
            HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusLayout.createSequentialGroup()
                .addGroup(HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HapusLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel29))
                    .addGroup(HapusLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel28)))
                .addGap(851, 851, 851))
        );
        HapusLayout.setVerticalGroup(
            HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HapusLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(398, 398, 398))
        );

        root.add(Hapus, "menuHapus");

        menutama.setBackground(new java.awt.Color(172, 226, 219));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel24.setText("Welcome, Silakan Pilih ");

        javax.swing.GroupLayout menutamaLayout = new javax.swing.GroupLayout(menutama);
        menutama.setLayout(menutamaLayout);
        menutamaLayout.setHorizontalGroup(
            menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutamaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel24)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        menutamaLayout.setVerticalGroup(
            menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel24)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        root.add(menutama, "menuUtama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hapus;
    private javax.swing.JPanel MilihEdit;
    private javax.swing.JPanel Step1;
    private javax.swing.JPanel Step2;
    private javax.swing.JPanel Step3;
    private javax.swing.JPanel Step4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menutama;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
