/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;
import java.sql.DriverManager;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Realfi
 */
public class mahasiswa extends javax.swing.JFrame {
String nama,email,alamat,jk,agama,notelp,nrp,prodi,status,namaAyah,namaIbu,ktpAyah,notelpOrtu,alamatOrtu,photoname;
Connection con;
PreparedStatement pst;
Statement stm;
ResultSet rs;
JFileChooser jfc;
File file;
    /**
     * Creates new form mahasiswa
     */
    public mahasiswa() {
        initComponents();
        edit();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelamin = new javax.swing.ButtonGroup();
        root = new javax.swing.JPanel();
        Step1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        rdLk = new javax.swing.JRadioButton();
        rdPr = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox<>();
        txtPhone = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnBackInput = new javax.swing.JButton();
        Step2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNrp = new javax.swing.JTextField();
        cbProdi = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JCheckBox();
        btnNextS2 = new javax.swing.JButton();
        btnBackS2 = new javax.swing.JButton();
        Step3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNamaA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNamaIb = new javax.swing.JTextField();
        txtPhoneOrtu = new javax.swing.JTextField();
        txtKtpA = new javax.swing.JTextField();
        txtAlamatOrtu = new javax.swing.JTextField();
        btnBackS3 = new javax.swing.JButton();
        btnNextS3 = new javax.swing.JButton();
        Step4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtfileTest = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBackS4 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        btnPilih = new javax.swing.JButton();
        MilihEdit = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnLanjut = new javax.swing.JButton();
        lbImgEdit = new javax.swing.JLabel();
        btnBackEdit = new javax.swing.JButton();
        Hapus = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMahasiswaHps = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        lbImgHps = new javax.swing.JLabel();
        btnBackHps = new javax.swing.JButton();
        menutama = new javax.swing.JPanel();
        btnInput = new javax.swing.JButton();
        btnEditLp = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        btnHapusLp = new javax.swing.JButton();
        btHapus1 = new javax.swing.JButton();
        btnCetakMhs = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        root.setLayout(new java.awt.CardLayout());

        Step1.setBackground(new java.awt.Color(172, 226, 219));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel2.setText("- Step 1 of 4");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel3.setText("Input Data ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nama");

        txtAlamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rdLk.setBackground(new java.awt.Color(172, 226, 219));
        kelamin.add(rdLk);
        rdLk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdLk.setText("Laki-Laki");

        rdPr.setBackground(new java.awt.Color(172, 226, 219));
        kelamin.add(rdPr);
        rdPr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdPr.setText("Perempuan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No Telepon");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Agama");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbAgama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Agama Anda", "Islam", "Kristen", "Katolik", "Hindu", "Budha" }));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBackInput.setText("Kembali");
        btnBackInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Step1Layout = new javax.swing.GroupLayout(Step1);
        Step1.setLayout(Step1Layout);
        Step1Layout.setHorizontalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step1Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(Step1Layout.createSequentialGroup()
                                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Step1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(453, Short.MAX_VALUE))
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step1Layout.createSequentialGroup()
                                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step1Layout.createSequentialGroup()
                                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBackInput, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(346, 346, 346)))
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addGroup(Step1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rdLk)
                                .addGap(39, 39, 39)
                                .addComponent(rdPr))
                            .addGroup(Step1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        Step1Layout.setVerticalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdLk)
                            .addComponent(rdPr)))
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail)
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Step1Layout.createSequentialGroup()
                        .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(Step1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        root.add(Step1, "step1");

        Step2.setBackground(new java.awt.Color(172, 226, 219));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel9.setText("Input Data ");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel10.setText("- Step 2 of 4");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("NRP");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Status");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Prodi");

        txtNrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbProdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi Anda", "TI", "SI", "DKV" }));
        cbProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdiActionPerformed(evt);
            }
        });

        cbStatus.setBackground(new java.awt.Color(172, 226, 219));
        cbStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbStatus.setText("Aktif");

        btnNextS2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNextS2.setText("Next");
        btnNextS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextS2ActionPerformed(evt);
            }
        });

        btnBackS2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackS2.setText("Back");
        btnBackS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Step2Layout = new javax.swing.GroupLayout(Step2);
        Step2.setLayout(Step2Layout);
        Step2Layout.setHorizontalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addGroup(Step2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11))
                            .addComponent(jLabel13)))
                    .addGroup(Step2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNrp, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnBackS2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNextS2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        Step2Layout.setVerticalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(66, 66, 66)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(txtNrp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(cbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNextS2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackS2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        root.add(Step2, "step2");

        Step3.setBackground(new java.awt.Color(172, 226, 219));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel14.setText("Input Data ");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel15.setText("- Step 3 of 4");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nama Ayah");

        txtNamaA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nama Ibu");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("No KTP Ayah");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("No Telpon Orang Tua");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Alamat Orang Tua");

        txtNamaIb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPhoneOrtu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtKtpA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAlamatOrtu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBackS3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackS3.setText("Back");
        btnBackS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackS3ActionPerformed(evt);
            }
        });

        btnNextS3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNextS3.setText("Next");
        btnNextS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextS3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Step3Layout = new javax.swing.GroupLayout(Step3);
        Step3.setLayout(Step3Layout);
        Step3Layout.setHorizontalGroup(
            Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step3Layout.createSequentialGroup()
                        .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(Step3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(Step3Layout.createSequentialGroup()
                                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addGroup(Step3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtNamaA, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtKtpA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlamatOrtu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaIb, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17)
                                    .addComponent(txtPhoneOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(Step3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBackS3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextS3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        Step3Layout.setVerticalGroup(
            Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(34, 34, 34)
                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Step3Layout.createSequentialGroup()
                        .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaIb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKtpA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPhoneOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamatOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(Step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackS3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextS3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        root.add(Step3, "step3");

        Step4.setBackground(new java.awt.Color(172, 226, 219));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel21.setText("Input Data ");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel22.setText("- Step 4 of 4");

        txtfileTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setText("Finish");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBackS4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBackS4.setText("Back");
        btnBackS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackS4ActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnPilih.setText("Pilih");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Step4Layout = new javax.swing.GroupLayout(Step4);
        Step4.setLayout(Step4Layout);
        Step4Layout.setHorizontalGroup(
            Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step4Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnBackS4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(Step4Layout.createSequentialGroup()
                .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Step4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(Step4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Step4Layout.createSequentialGroup()
                                .addComponent(txtfileTest, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Step4Layout.setVerticalGroup(
            Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(33, 33, 33)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfileTest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Step4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackS4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        root.add(Step4, "step4");

        MilihEdit.setBackground(new java.awt.Color(172, 226, 219));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel26.setText("Edit Entry Data");

        tbMahasiswa.setBackground(new java.awt.Color(172, 226, 219));
        tbMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NRP", "Nama", "Agama", "Jenis Kelamin", "Alamat", "Email", "Nomer Hp", "Prodi", "Status", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ));
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMahasiswa);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Pilih Data");

        btnLanjut.setText("Lanjutkan");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });

        lbImgEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnBackEdit.setText("Back");
        btnBackEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MilihEditLayout = new javax.swing.GroupLayout(MilihEdit);
        MilihEdit.setLayout(MilihEditLayout);
        MilihEditLayout.setHorizontalGroup(
            MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilihEditLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MilihEditLayout.createSequentialGroup()
                        .addComponent(btnBackEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MilihEditLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel27))
                    .addComponent(jLabel26)
                    .addGroup(MilihEditLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MilihEditLayout.setVerticalGroup(
            MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilihEditLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbImgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(MilihEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        root.add(MilihEdit, "milihEdit");

        Hapus.setBackground(new java.awt.Color(172, 226, 219));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel28.setText("Hapus Data");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Pilih Data");

        tbMahasiswaHps.setBackground(new java.awt.Color(172, 226, 219));
        tbMahasiswaHps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NRP", "Nama", "Agama", "Jenis Kelamin", "Alamat", "Email", "Nomer Hp", "Prodi", "Status", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ));
        tbMahasiswaHps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaHpsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMahasiswaHps);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        lbImgHps.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnBackHps.setText("Kembali");
        btnBackHps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHpsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HapusLayout = new javax.swing.GroupLayout(Hapus);
        Hapus.setLayout(HapusLayout);
        HapusLayout.setHorizontalGroup(
            HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusLayout.createSequentialGroup()
                .addGroup(HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HapusLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel29))
                    .addGroup(HapusLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HapusLayout.createSequentialGroup()
                                .addComponent(btnBackHps, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28)
                            .addGroup(HapusLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbImgHps, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        HapusLayout.setVerticalGroup(
            HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HapusLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImgHps, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(HapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackHps, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        root.add(Hapus, "menuHapus");

        menutama.setBackground(new java.awt.Color(172, 226, 219));

        btnInput.setText("input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnEditLp.setText("Edit");
        btnEditLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLpActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 26)); // NOI18N
        jLabel24.setText("Welcome, Silakan Pilih ");

        btnHapusLp.setText("Hapus");
        btnHapusLp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusLpActionPerformed(evt);
            }
        });

        btHapus1.setText("Menu Utama");
        btHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapus1ActionPerformed(evt);
            }
        });

        btnCetakMhs.setText("Cetak Report");
        btnCetakMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakMhsActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("Halaman Mahasiswa");

        javax.swing.GroupLayout menutamaLayout = new javax.swing.GroupLayout(menutama);
        menutama.setLayout(menutamaLayout);
        menutamaLayout.setHorizontalGroup(
            menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutamaLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(btnEditLp, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnHapusLp, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menutamaLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnCetakMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(menutamaLayout.createSequentialGroup()
                .addGroup(menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menutamaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel24))
                    .addGroup(menutamaLayout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menutamaLayout.setVerticalGroup(
            menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menutamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel24)
                .addGap(68, 68, 68)
                .addComponent(jLabel25)
                .addGap(44, 44, 44)
                .addGroup(menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditLp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusLp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(menutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        root.add(menutama, "menuUtama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void clearInput()
    {
        txtNama.setText("");
        txtEmail.setText("");
        txtAlamat.setText("");
        cbAgama.setSelectedIndex(0);
        cbProdi.setSelectedIndex(0);
        cbStatus.setSelected(false);
        rdLk.setSelected(false);
        rdPr.setSelected(false);
        txtPhone.setText("");
        txtPhoneOrtu.setText("");
        txtNrp.setText("");
        txtNamaA.setText("");
        txtNamaIb.setText("");
        txtKtpA.setText("");
        txtfileTest.setText("");
        
    }
    
    public void load_table()
    {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NRP");
        model.addColumn("Nama");
        model.addColumn("Prodi");
        model.addColumn("Status");
        model.addColumn("JK");
        model.addColumn("Agama");
        model.addColumn("Alamat");
        model.addColumn("Email");
        model.addColumn("Notelp");
        model.addColumn("Nama Ayah");
        model.addColumn("No KTP Ayah");
        model.addColumn("Nama Ibu");
        model.addColumn("NoTelp Ortu");
        model.addColumn("Alamat Ortu");
        model.addColumn("photopath");
        
        
        
        try {
         
            String sql = "select * from mahasiswa";
            con = (Connection) config.configDB();
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            
            while(rs.next())
            {
                model.addRow(
                new Object[]
                {
                    rs.getString("nrp"),rs.getString("nama_mahasiswa"),rs.getString("prodi"),rs.getString("Status"),rs.getString("JK"),rs.getString("agama"),rs.getString("alamat"),rs.getString("email"),rs.getString("notelp"),rs.getString("namaAyah"),rs.getString("noKTPAyah"),rs.getString("namaIbu"),rs.getString("noTelpOrtu"),rs.getString("almtOrtu"),rs.getString("photopath")
                }
                );
            }
            tbMahasiswa.setModel(model);
            tbMahasiswaHps.setModel(model);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void edit()
    {
        String sql = "select * from mahasiswa where nrp=?";
        try {
            con = config.configDB();
            pst = con.prepareStatement(sql);
            String nrpEdit = txtNrp.getText();
            pst.setString(1, nrpEdit);
            rs = pst.executeQuery();
            if(rs.next())
            {
                btnEdit.setEnabled(true);
                btnSubmit.setEnabled(false);
            }
            else{
                btnEdit.setEnabled(false);
                btnSubmit.setEnabled(true);
            }
        } catch (Exception e) {
        }
    }
    
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        nama = txtNama.getText();
        email = txtEmail.getText();
        alamat = txtAlamat.getText();
        if (rdLk.isSelected())
        {
            jk = "Laki - Laki";
        }
        if (rdPr.isSelected()) {
            jk = "Perempuan";
        }
        agama = cbAgama.getSelectedItem().toString();
        notelp = txtPhone.getText();
        cl.show(root, "step2");
        String sql = "select nrp from mahasiswa";
        try {
            con = config.configDB();
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            if (rs.next())
            {
                if(txtNrp.getText().equals(rs.getString(1)) || txtNrp.getText() != "")
                {
                    txtNrp.setEditable(false);
                }
                else
                {
                    txtNrp.setEditable(true);
                }
            }
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void cbProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdiActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "step1");
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnBackS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackS2ActionPerformed
        // TODO add your handling code here:\
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "step1");
        txtNama.setText(nama);
        txtEmail.setText(email);
        txtPhone.setText(notelp);
        if(jk.equals("Laki - Laki"))
        {
            rdLk.setSelected(true);
        }
        if(jk.equals("Perempuan"))
        {
            rdPr.setSelected(true);
        }
        cbAgama.setSelectedItem(agama);
        txtAlamat.setText(alamat);
    }//GEN-LAST:event_btnBackS2ActionPerformed

    private void btnNextS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextS2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        nrp = txtNrp.getText();
        prodi = cbProdi.getSelectedItem().toString();
        status = "";
        if (cbStatus.isSelected())
        {
            status+=cbStatus.getText()+"";
        }
        else
        {
            status+="Tidak Aktif";
        }
        cl.show(root, "step3");
    }//GEN-LAST:event_btnNextS2ActionPerformed

    private void btnBackS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackS3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "step2");
        txtNrp.setText(nrp);
        cbProdi.setSelectedItem(prodi);
        if (status.equals("Aktif"))
        {
            cbStatus.setSelected(true);
        }
        if (status.equals("Tidak Aktif"))
        {
            cbStatus.setSelected(false);
        }
    }//GEN-LAST:event_btnBackS3ActionPerformed

    private void btnNextS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextS3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        namaAyah = txtNamaA.getText();
        namaIbu = txtNamaIb.getText();
        ktpAyah = txtKtpA.getText();
        notelpOrtu = txtPhoneOrtu.getText();
        alamatOrtu = txtAlamatOrtu.getText();
        edit();
        try {
            Toolkit toolkit=Toolkit.getDefaultToolkit();

            String path=new File(".").getCanonicalPath();
            Image image=toolkit.getImage(path+"/image/"+photoname); 
            Image imagedResized=image.getScaledInstance(lbImage.getWidth(), lbImage.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icon=new ImageIcon(imagedResized);
            lbImage.setIcon(icon); 
        } catch (Exception e) {
        }
        cl.show(root, "step4");
    }//GEN-LAST:event_btnNextS3ActionPerformed

    private void btnBackS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackS4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        txtNamaA.setText(namaAyah);
        txtNamaIb.setText(namaIbu);
        txtKtpA.setText(ktpAyah);
        txtPhoneOrtu.setText(notelpOrtu);
        txtAlamatOrtu.setText(alamatOrtu);
        cl.show(root, "step3");
    }//GEN-LAST:event_btnBackS4ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String sql="insert into mahasiswa(nrp,nama_mahasiswa,prodi,status,jk,agama,alamat,email,notelp,namaayah,noktpayah,namaibu,notelportu,almtortu,photopath) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            CardLayout cl = (CardLayout) root.getLayout();
            con = config.configDB();
            pst = con.prepareStatement(sql);
            pst.setString(1, nrp);
            pst.setString(2, nama);
            pst.setString(3, prodi);
            pst.setString(4, status);
            pst.setString(5, jk);
            pst.setString(6, agama);
            pst.setString(7, alamat);
            pst.setString(8, email);
            pst.setString(9, notelp);
            pst.setString(10, namaAyah);
            pst.setString(11, ktpAyah);
            pst.setString(12, namaIbu);
            pst.setString(13, notelpOrtu);
            pst.setString(14, alamatOrtu);
            pst.setString(15, txtfileTest.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil input data");
            String path = new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image"));
            DefaultTableModel model = (DefaultTableModel) tbMahasiswa.getModel();
            model.setRowCount(0);
            load_table();
            cl.show(root, "menuUtama");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_formWindowActivated

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String sql = "update mahasiswa set nama_mahasiswa=?, prodi=?, status=?, jk=?, agama=?, alamat=?, email=?, notelp=?, namaayah=?, noktpayah=?, namaibu=?, notelportu=?, almtortu=?, photopath=? where nrp=?";
        try {
            CardLayout cl = (CardLayout) root.getLayout();
            con = config.configDB();
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, prodi);
            pst.setString(3, status);
            pst.setString(4, jk);
            pst.setString(5, agama);
            pst.setString(6, alamat);
            pst.setString(7, email);
            pst.setString(8, notelp);
            pst.setString(9, namaAyah);
            pst.setString(10, ktpAyah);
            pst.setString(11, namaIbu);
            pst.setString(12, notelpOrtu);
            pst.setString(13, alamatOrtu);
            pst.setString(14, txtfileTest.getText());
            pst.setString(15, nrp);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil Update data");
            String path = new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image"));
            DefaultTableModel model = (DefaultTableModel) tbMahasiswa.getModel();
            model.setRowCount(0);
            load_table();
            cl.show(root, "menuUtama");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLpActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "milihEdit");
    }//GEN-LAST:event_btnEditLpActionPerformed

    private void tbMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaMouseClicked
        // TODO add your handling code here:
        
        int baris = tbMahasiswa.rowAtPoint(evt.getPoint());
        nrp = tbMahasiswa.getValueAt(baris, 0).toString();
        nama = tbMahasiswa.getValueAt(baris, 1).toString();
        prodi = tbMahasiswa.getValueAt(baris, 2).toString();
        status = tbMahasiswa.getValueAt(baris, 3).toString();
        jk = tbMahasiswa.getValueAt(baris, 4).toString();
        agama = tbMahasiswa.getValueAt(baris, 5).toString();
        alamat = tbMahasiswa.getValueAt(baris, 6).toString();
        email = tbMahasiswa.getValueAt(baris, 7).toString();
        notelp = tbMahasiswa.getValueAt(baris, 8).toString();
        namaAyah = tbMahasiswa.getValueAt(baris, 9).toString();
        ktpAyah = tbMahasiswa.getValueAt(baris, 10).toString();
        namaIbu = tbMahasiswa.getValueAt(baris, 11).toString();
        notelpOrtu = tbMahasiswa.getValueAt(baris, 12).toString();
        alamatOrtu = tbMahasiswa.getValueAt(baris, 13).toString();
        photoname = tbMahasiswa.getValueAt(baris, 14).toString();
        
        txtNama.setText(nama);
        txtEmail.setText(email);
        txtAlamat.setText(alamat);
        if(jk.equals("Laki - Laki"))
        {
            rdLk.setSelected(true);
        }
        if (jk.equals("Perempuan"))
        {
            rdPr.setSelected(true);
        }
        cbAgama.setSelectedItem(agama);
        txtPhone.setText(notelp);
        txtNrp.setText(nrp);
        cbProdi.setSelectedItem(prodi);
        if (status.equals("Aktif"))
        {
            cbStatus.setSelected(true);
        }
        else
        {
            cbStatus.setSelected(false);
        }
        txtNamaA.setText(namaAyah);
        txtNamaIb.setText(namaIbu);
        txtKtpA.setText(ktpAyah);
        txtPhoneOrtu.setText(notelpOrtu);
        txtAlamatOrtu.setText(alamatOrtu);
        txtfileTest.setText(photoname);
        
        try {
            Toolkit toolkit=Toolkit.getDefaultToolkit();

            String path=new File(".").getCanonicalPath();
            Image image=toolkit.getImage(path+"/image/"+photoname); 
            Image imagedResized=image.getScaledInstance(lbImgEdit.getWidth(), lbImgEdit.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icon=new ImageIcon(imagedResized);
            lbImgEdit.setIcon(icon); 
            
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_tbMahasiswaMouseClicked

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "step1");
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        jfc = new JFileChooser();
        if (jfc.showOpenDialog(lbImage) == JFileChooser.APPROVE_OPTION)
        {
            Toolkit tk = Toolkit.getDefaultToolkit();
            Image img = tk.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imgRsz = img.getScaledInstance(lbImage.getWidth(), lbImage.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon imgIcon = new ImageIcon(imgRsz);
            
            lbImage.setIcon(imgIcon);
            txtfileTest.setText(jfc.getSelectedFile().getName());
            file = new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String sql = "delete from mahasiswa where nrp=?";
        int option = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus ini ?","Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION)
        {
            try {
                CardLayout cl = (CardLayout) root.getLayout();
                con = config.configDB();
                pst = con.prepareStatement(sql);
                pst.setString(1, nrp);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil Delete data");
                DefaultTableModel model = (DefaultTableModel) tbMahasiswa.getModel();
                model.setRowCount(0);
                load_table();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
        }
        else{
            JOptionPane.showMessageDialog(null, "Tidak jadi Delete");
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tbMahasiswaHpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaHpsMouseClicked
        // TODO add your handling code here:
        int baris = tbMahasiswa.rowAtPoint(evt.getPoint());
        nrp = tbMahasiswa.getValueAt(baris, 0).toString();
        nama = tbMahasiswa.getValueAt(baris, 1).toString();
        prodi = tbMahasiswa.getValueAt(baris, 2).toString();
        status = tbMahasiswa.getValueAt(baris, 3).toString();
        jk = tbMahasiswa.getValueAt(baris, 4).toString();
        agama = tbMahasiswa.getValueAt(baris, 5).toString();
        alamat = tbMahasiswa.getValueAt(baris, 6).toString();
        email = tbMahasiswa.getValueAt(baris, 7).toString();
        notelp = tbMahasiswa.getValueAt(baris, 8).toString();
        namaAyah = tbMahasiswa.getValueAt(baris, 9).toString();
        ktpAyah = tbMahasiswa.getValueAt(baris, 10).toString();
        namaIbu = tbMahasiswa.getValueAt(baris, 11).toString();
        notelpOrtu = tbMahasiswa.getValueAt(baris, 12).toString();
        alamatOrtu = tbMahasiswa.getValueAt(baris, 13).toString();
        photoname = tbMahasiswa.getValueAt(baris, 14).toString();
        
        try {
            Toolkit toolkit=Toolkit.getDefaultToolkit();

            String path=new File(".").getCanonicalPath();
            Image image=toolkit.getImage(path+"/image/"+photoname); 
            Image imagedResized=image.getScaledInstance(lbImgHps.getWidth(), lbImgHps.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icon=new ImageIcon(imagedResized);
            lbImgHps.setIcon(icon); 
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_tbMahasiswaHpsMouseClicked

    private void btnHapusLpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLpActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "menuHapus");
    }//GEN-LAST:event_btnHapusLpActionPerformed

    private void btnBackEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackEditActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "menuUtama");
        clearInput();
    }//GEN-LAST:event_btnBackEditActionPerformed

    private void btnBackHpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHpsActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "menuUtama");
    }//GEN-LAST:event_btnBackHpsActionPerformed

    private void btnBackInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackInputActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) root.getLayout();
        cl.show(root, "menuUtama");
    }//GEN-LAST:event_btnBackInputActionPerformed

    private void btHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapus1ActionPerformed
        this.dispose();
        landingpage lp = new landingpage();
        lp.setVisible(true);
    }//GEN-LAST:event_btHapus1ActionPerformed

    private void btnCetakMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakMhsActionPerformed
        try{
            String jrmxlFile ="src/Report/mahasiswaReport.jrxml";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahasiswa_sakti", "root", "");
            HashMap param = new HashMap();
            JasperReport jspR = JasperCompileManager.compileReport(jrmxlFile);
            JasperPrint JPrint = JasperFillManager.fillReport(jspR, param, con);
            JasperViewer.viewReport(JPrint,false);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnCetakMhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hapus;
    private javax.swing.JPanel MilihEdit;
    private javax.swing.JPanel Step1;
    private javax.swing.JPanel Step2;
    private javax.swing.JPanel Step3;
    private javax.swing.JPanel Step4;
    private javax.swing.JButton btHapus1;
    private javax.swing.JButton btnBackEdit;
    private javax.swing.JButton btnBackHps;
    private javax.swing.JButton btnBackInput;
    private javax.swing.JButton btnBackS2;
    private javax.swing.JButton btnBackS3;
    private javax.swing.JButton btnBackS4;
    private javax.swing.JButton btnCetakMhs;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditLp;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusLp;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNextS2;
    private javax.swing.JButton btnNextS3;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JCheckBox cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup kelamin;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbImgEdit;
    private javax.swing.JLabel lbImgHps;
    private javax.swing.JPanel menutama;
    private javax.swing.JRadioButton rdLk;
    private javax.swing.JRadioButton rdPr;
    private javax.swing.JPanel root;
    private javax.swing.JTable tbMahasiswa;
    private javax.swing.JTable tbMahasiswaHps;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAlamatOrtu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKtpA;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaA;
    private javax.swing.JTextField txtNamaIb;
    private javax.swing.JTextField txtNrp;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhoneOrtu;
    private javax.swing.JTextField txtfileTest;
    // End of variables declaration//GEN-END:variables
}
